# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: power_reviews 0.3.1 ruby lib

Gem::Specification.new do |s|
  s.name = "power_reviews"
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Beau Collins"]
  s.date = "2014-01-22"
  s.description = "Tools and library for integrating Power Reviews into a rails website."
  s.email = "beaucollins@gmail.com"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "generators/power_reviews/USAGE",
    "generators/power_reviews/power_reviews_generator.rb",
    "generators/power_reviews/templates/config/initializers/power_reviews.rb",
    "generators/power_reviews/templates/config/power_reviews.yml",
    "generators/power_reviews/templates/config/schedule.rb",
    "generators/power_reviews/templates/lib/tasks/power_reviews_tasks.rake",
    "lib/power_reviews.rb",
    "lib/power_reviews/config.rb",
    "lib/power_reviews/feed.rb",
    "lib/power_reviews/feed_item.rb",
    "lib/power_reviews/protocols/base.rb",
    "lib/power_reviews/protocols/cp.rb",
    "lib/power_reviews/protocols/ftp.rb",
    "lib/power_reviews/review_data.rb",
    "lib/power_reviews/routes.rb",
    "lib/power_reviews/sync.rb",
    "lib/power_reviews/view_helpers.rb",
    "power_reviews.gemspec",
    "rails/init.rb",
    "test/fixtures/rawdata/review_data_complete.xml",
    "test/fixtures/rawdata/review_data_complete.xsd",
    "test/fixtures/rawdata/review_data_summary.xml",
    "test/fixtures/rawdata/review_data_summary.xsd",
    "test/power_reviews/config_test.rb",
    "test/power_reviews/review_data_test.rb",
    "test/power_reviews/view_helpers_test.rb",
    "test/power_reviews_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/beaucollins/power_reviews"
  s.rubygems_version = "2.2.1"
  s.summary = "Helps integrate Power Reviews into a rails site"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<whenever>, [">= 0"])
      s.add_runtime_dependency(%q<fastercsv>, [">= 0"])
      s.add_development_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<whenever>, [">= 0"])
      s.add_dependency(%q<fastercsv>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<whenever>, [">= 0"])
    s.add_dependency(%q<fastercsv>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

